TODO:  filter removing genders with just one song
a lot of problem filtering with pandas. Errors maybe because of the environment.
Error to solve:
ValueError: The least populated class in y has only 1 member, which is too few.

ERROR TO SOLVE: The minimum number of groups for any class cannot be less than 2.